name: 'Delete untagged verions'
description: 'Delete untagged versins from ghcr.io package'
inputs:
  token:
    description: 'PAT with delete:packages scope'
    required: true
  owner:
    description: 'Owner of the package'
    required: true
  package:
    description: 'Name of the package'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
