on: [push]

jobs:
  delete_untagged:
    runs-on: ubuntu-latest
    name: A job to delete untagged versions
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Delete untagged versions step
        uses: ./ # Uses an action in the root directory
        with:
          owner: jcansdale-test
          package: kipp2
          token: ${{ secrets.DELETE_PACKAGES_TOKEN }}
